using UnrealBuildTool;
using System.IO;

public class Uika : ModuleRules
{
    public Uika(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        // Read module dependencies generated by uika-codegen.
        // Falls back to Core + CoreUObject + Engine if the file doesn't exist yet.
        string DepsFile = Path.Combine(ModuleDirectory, "Generated", "module_deps.txt");
        if (File.Exists(DepsFile))
        {
            string[] Modules = File.ReadAllLines(DepsFile);
            foreach (string Module in Modules)
            {
                string Trimmed = Module.Trim();
                if (Trimmed.Length > 0)
                {
                    PublicDependencyModuleNames.Add(Trimmed);
                }
            }
        }
        else
        {
            PublicDependencyModuleNames.AddRange(new string[]
            {
                "Core",
                "CoreUObject",
                "Engine",
            });
        }
    }
}
