// ShooterWeapon: the Shooter variant's `AShooterWeapon` in Rust, the base of
// the weapons (`BP_ShooterWeapon_Pistol`, `_Rifle`, `_GrenadeLauncher`): first
// and third person meshes, ammo and firing, projectiles spawned towards where
// its holder aims. It talks to its holder, the actor that owns it, through
// the `ShooterWeaponHolder` trait.

use bindings::engine::{
    Actor, ActorExt, AnimInstance, AnimMontage, EFirstPersonPrimitiveType,
    ESpawnActorCollisionHandlingMethod, ESpawnActorScaleMethod, GameplayStatics,
    KismetMathLibrary, KismetSystemLibrary, Pawn, PrimitiveComponentExt, SceneComponent,
    SceneComponentExt, SkeletalMeshComponent,
};
use bindings::prelude::*;
use glam::DVec3;
use rusteal_runtime::runtime::{
    FName, LOG_WARNING, OwnedStruct, RustealResult, SubclassOf, UObjectRef, ulog,
};
use rusteal_runtime::{uclass, uclass_impl};

use super::model::{self, TriggerPull};
use super::projectile::ShooterProjectile;
use super::weapon_holder::{ShooterWeaponHolder, weapon_holder};

#[uclass(parent = Actor)]
pub struct ShooterWeapon {
    #[component(root, name = "Root")]
    root: SceneComponent,

    /// First person perspective mesh
    #[component(attach = "root", name = "First Person Mesh")]
    first_person_mesh: SkeletalMeshComponent,

    /// Third person perspective mesh
    #[component(attach = "root", name = "Third Person Mesh")]
    third_person_mesh: SkeletalMeshComponent,

    /// Type of projectiles this weapon will shoot
    #[uproperty(EditAnywhere, category = "Ammo")]
    projectile_class: SubclassOf<ShooterProjectile>,

    /// Number of bullets in a magazine
    #[uproperty(EditAnywhere, category = "Ammo", default = 10)]
    magazine_size: i32,

    /// Number of bullets in the current magazine
    #[uproperty]
    current_bullets: i32,

    /// Animation montage to play when firing this weapon
    #[uproperty(EditAnywhere, category = "Animation")]
    firing_montage: UObjectRef<AnimMontage>,

    /// AnimInstance class to set for the first person character mesh when this weapon is active
    #[uproperty(EditAnywhere, category = "Animation")]
    first_person_anim_instance_class: SubclassOf<AnimInstance>,

    /// AnimInstance class to set for the third person character mesh when this weapon is active
    #[uproperty(EditAnywhere, category = "Animation")]
    third_person_anim_instance_class: SubclassOf<AnimInstance>,

    /// Cone half-angle for variance while aiming
    #[uproperty(EditAnywhere, category = "Aim", default = 0.0)]
    aim_variance: f32,

    /// Amount of firing recoil to apply to the owner
    #[uproperty(EditAnywhere, category = "Aim", default = 0.0)]
    firing_recoil: f32,

    /// Name of the first person muzzle socket where projectiles will spawn
    #[uproperty(EditAnywhere, category = "Aim")]
    muzzle_socket_name: FName,

    /// Distance ahead of the muzzle that bullets will spawn at
    #[uproperty(EditAnywhere, category = "Aim", default = 10.0)]
    muzzle_offset: f32,

    /// If true, this weapon will automatically fire at the refire rate
    #[uproperty(EditAnywhere, category = "Refire", default = false)]
    b_full_auto: bool,

    /// Time between shots for this weapon. Affects both full auto and semi auto modes
    #[uproperty(EditAnywhere, category = "Refire", default = 0.5)]
    refire_rate: f32,

    /// Loudness of the shot for AI perception system interactions
    #[uproperty(EditAnywhere, category = "Perception", default = 1.0)]
    shot_loudness: f32,

    /// Max range of shot AI perception noise
    #[uproperty(EditAnywhere, category = "Perception", default = 300.0)]
    shot_noise_range: f32,

    /// Tag to apply to noise generated by shooting this weapon
    #[uproperty(EditAnywhere, category = "Perception")]
    noise_owner_tag: FName,

    /// Game time of last shot fired, used to enforce refire rate on semi auto
    time_of_last_shot: f32,

    /// If true, the weapon is currently firing
    is_firing: bool,
}

#[uclass_impl]
impl ShooterWeapon {
    /// Everything `AShooterWeapon::AShooterWeapon()` sets.
    #[class_defaults]
    fn class_defaults(&mut self) -> RustealResult<()> {
        self.set_noise_owner_tag(FName::new("Shot"));

        // create the first person mesh
        let first_person = self.first_person_mesh()?.checked()?;
        first_person.set_collision_profile_name(FName::new("NoCollision").handle(), Some(true));
        first_person.set_first_person_primitive_type(EFirstPersonPrimitiveType::FirstPerson);
        first_person.set_only_owner_see(true);

        // create the third person mesh
        let third_person = self.third_person_mesh()?.checked()?;
        third_person.set_collision_profile_name(FName::new("NoCollision").handle(), Some(true));
        third_person.set_first_person_primitive_type(EFirstPersonPrimitiveType::WorldSpaceRepresentation);
        third_person.set_owner_no_see(true);
        Ok(())
    }

    /// Gameplay initialization
    #[ufunction(Override)]
    fn receive_begin_play(&mut self) {
        if let Err(e) = self.begin_play() {
            ulog!(LOG_WARNING, "[Shooter] weapon BeginPlay failed: {e}");
        }
    }

    /// Gameplay Cleanup
    #[ufunction(Override)]
    fn receive_end_play(&mut self, _end_play_reason: u8) {
        // clear the refire timer
        self.clear_refire_timer();
    }

    /// Fire the weapon
    #[ufunction]
    fn fire(&mut self) {
        // ensure the player still wants to fire. They may have let go of the trigger
        if !self.is_firing() {
            return;
        }
        let Some(mut holder) = self.holder() else {
            return;
        };

        // fire a projectile at the target
        let target = holder.get_weapon_target_location();
        if let Err(e) = self.fire_projectile(holder.as_mut(), target) {
            ulog!(LOG_WARNING, "[Shooter] firing failed: {e}");
        }

        let world = self.as_ref().upcast_to();
        let Ok(me) = self.as_ref().checked() else {
            return;
        };

        // update the time of our last shot
        self.set_time_of_last_shot(GameplayStatics::get_time_seconds(world) as f32);

        // make noise so the AI perception system can hear us
        let pawn_owner = self.pawn_owner();
        if let Ok(pawn) = pawn_owner.checked() {
            me.make_noise(
                Some(self.shot_loudness()),
                Some(pawn_owner),
                &pawn.k2_get_actor_location(),
                Some(self.shot_noise_range()),
                Some(self.noise_owner_tag().handle()),
            );
        }

        // are we full auto? schedule the next shot; for semi-auto weapons,
        // schedule the cooldown notification
        let next = if self.b_full_auto() { "Fire" } else { "FireCooldownExpired" };
        self.set_refire_timer(next, self.refire_rate());
    }

    /// Called when the refire rate time has passed while shooting semi auto weapons
    #[ufunction]
    fn fire_cooldown_expired(&mut self) {
        // notify the owner
        if let Some(mut holder) = self.holder() {
            holder.on_semi_weapon_refire();
        }
    }

    /// Returns the first person mesh
    #[ufunction(BlueprintPure, name = "GetFirstPersonMesh")]
    fn get_first_person_mesh(&self) -> UObjectRef<SkeletalMeshComponent> {
        self.first_person_mesh().unwrap_or_default()
    }

    /// Returns the third person mesh
    #[ufunction(BlueprintPure, name = "GetThirdPersonMesh")]
    fn get_third_person_mesh(&self) -> UObjectRef<SkeletalMeshComponent> {
        self.third_person_mesh().unwrap_or_default()
    }
}

impl ShooterWeapon {
    /// Spawns a weapon of `class` held by `holder`: owned and instigated by it
    /// before its BeginPlay, as `SpawnActor` with Owner and Instigator.
    pub fn spawn_for(holder: UObjectRef<Pawn>, class: SubclassOf<ShooterWeapon>) -> RustealResult<UObjectRef<ShooterWeapon>> {
        let transform = holder.checked()?.get_transform();
        let spawned = GameplayStatics::begin_deferred_actor_spawn_from_class(
            holder.upcast_to(),
            class.upcast_to(),
            &transform,
            Some(ESpawnActorCollisionHandlingMethod::AlwaysSpawn),
            Some(holder.upcast_to()),
            Some(ESpawnActorScaleMethod::MultiplyWithRoot),
        );
        spawned.checked()?.set_instigator(holder);
        let spawned = GameplayStatics::finish_spawning_actor(spawned, &transform, Some(ESpawnActorScaleMethod::MultiplyWithRoot));
        spawned.cast()
    }

    /// The actor holding this weapon, as `Cast<IShooterWeaponHolder>(GetOwner())`.
    fn holder(&self) -> Option<Box<dyn ShooterWeaponHolder>> {
        weapon_holder(self.as_ref().checked().ok()?.get_owner())
    }

    /// The owner as a pawn, for AI perception noise.
    fn pawn_owner(&self) -> UObjectRef<Pawn> {
        self.as_ref()
            .checked()
            .ok()
            .and_then(|me| me.get_owner().cast().ok())
            .unwrap_or_default()
    }

    fn begin_play(&mut self) -> RustealResult<()> {
        let me = self.as_ref().checked()?;

        // subscribe to the owner's destroyed delegate
        let weapon = self.as_ref();
        me.get_owner()
            .checked()?
            .on_destroyed()
            .add(move |_destroyed_actor| {
                // ensure this weapon is destroyed when the owner is destroyed
                if let Ok(weapon) = weapon.checked() {
                    weapon.k2_destroy_actor();
                }
            })?
            .detach();

        // fill the first ammo clip
        self.set_current_bullets(self.magazine_size());

        // attach the meshes to the owner
        if let Some(mut holder) = self.holder() {
            holder.attach_weapon_meshes(self);
        }
        Ok(())
    }

    /// Activates this weapon and gets it ready to fire
    pub fn activate_weapon(&mut self, owner_tag: FName) {
        // save the owner tag for perception noise detection
        self.set_noise_owner_tag(owner_tag);

        // unhide this weapon
        if let Ok(me) = self.as_ref().checked() {
            me.set_actor_hidden_in_game(false);
        }

        // notify the owner
        if let Some(mut holder) = self.holder() {
            holder.on_weapon_activated(self);
        }
    }

    /// Deactivates this weapon
    pub fn deactivate_weapon(&mut self) {
        // ensure we're no longer firing this weapon while deactivated
        self.stop_firing();

        // hide the weapon
        if let Ok(me) = self.as_ref().checked() {
            me.set_actor_hidden_in_game(true);
        }

        // notify the owner
        if let Some(mut holder) = self.holder() {
            holder.on_weapon_deactivated(self);
        }
    }

    /// Start firing this weapon
    pub fn start_firing(&mut self) {
        // raise the firing flag
        self.set_is_firing(true);

        // check how much time has passed since we last shot
        let now = GameplayStatics::get_time_seconds(self.as_ref().upcast_to()) as f32;
        match model::pull_trigger(now - self.time_of_last_shot(), self.refire_rate(), self.b_full_auto()) {
            // fire the weapon right away
            TriggerPull::FireNow => self.fire(),
            // if we're full auto, schedule the next shot
            TriggerPull::FireIn(delay) => self.set_refire_timer("Fire", delay),
            TriggerPull::Wait => {}
        }
    }

    /// Stop firing this weapon
    pub fn stop_firing(&mut self) {
        // lower the firing flag
        self.set_is_firing(false);

        // clear the refire timer
        self.clear_refire_timer();
    }

    /// The refire timer: one timer, whichever function it calls.
    fn set_refire_timer(&self, function: &str, delay: f32) {
        self.clear_refire_timer();
        KismetSystemLibrary::k2_set_timer(self.as_ref().upcast_to(), function, delay, false, None, None, None);
    }

    fn clear_refire_timer(&self) {
        let me = self.as_ref().upcast_to();
        KismetSystemLibrary::k2_clear_timer(me, "Fire");
        KismetSystemLibrary::k2_clear_timer(me, "FireCooldownExpired");
    }

    /// Fire a projectile towards the target location
    fn fire_projectile(&mut self, holder: &mut dyn ShooterWeaponHolder, target_location: DVec3) -> RustealResult<()> {
        let me = self.as_ref().checked()?;

        // get the projectile transform
        let transform = self.calculate_projectile_spawn_transform(target_location)?;

        // spawn the projectile
        let spawned = GameplayStatics::begin_deferred_actor_spawn_from_class(
            me.as_ref().upcast_to(),
            self.projectile_class().upcast_to(),
            &transform,
            Some(ESpawnActorCollisionHandlingMethod::AlwaysSpawn),
            Some(me.get_owner()),
            Some(ESpawnActorScaleMethod::OverrideRootScale),
        );
        if let Ok(projectile) = spawned.checked() {
            projectile.set_instigator(self.pawn_owner());
        }
        let spawned = GameplayStatics::finish_spawning_actor(spawned, &transform, Some(ESpawnActorScaleMethod::OverrideRootScale));

        // set the noise tag on the projectile
        if let Ok(projectile) = ShooterProjectile::from_obj(spawned) {
            projectile.set_noise_tag(self.noise_owner_tag());
        }

        // play the firing montage
        holder.play_firing_montage(self.firing_montage());

        // add recoil
        holder.add_weapon_recoil(self.firing_recoil());

        // consume bullets
        self.set_current_bullets(model::bullets_after_shot(self.current_bullets(), self.magazine_size()));

        // update the weapon HUD
        holder.update_weapon_hud(self.current_bullets(), self.magazine_size());
        Ok(())
    }

    /// Calculates the spawn transform for projectiles shot by this weapon
    fn calculate_projectile_spawn_transform(&self, target_location: DVec3) -> RustealResult<OwnedStruct<FTransform>> {
        // find the muzzle location
        let muzzle = self
            .first_person_mesh()?
            .checked()?
            .get_socket_location(self.muzzle_socket_name().handle())
            .to_dvec3();

        // calculate the spawn location ahead of the muzzle
        let spawn = muzzle + (target_location - muzzle).normalize_or_zero() * f64::from(self.muzzle_offset());

        // find the aim rotation vector while applying some variance to the target
        let variance = KismetMathLibrary::random_unit_vector().to_dvec3() * f64::from(self.aim_variance());
        let aim = KismetMathLibrary::find_look_at_rotation(
            &FVector::from_dvec3(spawn),
            &FVector::from_dvec3(target_location + variance),
        );

        // return the built transform
        Ok(KismetMathLibrary::make_transform(
            &FVector::from_dvec3(spawn),
            &aim,
            &FVector::from_dvec3(DVec3::ONE),
        ))
    }

    /// Returns the current bullet count
    pub fn bullet_count(&self) -> i32 {
        self.current_bullets()
    }
}
