// C++ UikaFillFuncTable.cpp generation.

use std::collections::BTreeMap;

use crate::context::FuncEntry;
use crate::cpp_gen::wrapper::cpp_wrapper_name;

/// Generate the UikaFillFuncTable.cpp file.
pub fn generate_fill_table(
    entries: &[FuncEntry],
    _by_class: &BTreeMap<(String, String), Vec<&FuncEntry>>,
) -> String {
    let mut out = String::with_capacity(entries.len() * 80 + 1024);

    out.push_str("// Auto-generated by uika-codegen. Do not edit.\n\n");
    out.push_str("#include \"UikaFuncIds.h\"\n\n");

    // Forward-declare all wrapper functions
    out.push_str("// Forward declarations of wrapper functions\n");
    for entry in entries {
        let c_name = cpp_wrapper_name(&entry.class_name, &entry.func_name);
        out.push_str(&format!("extern \"C\" uint32_t {c_name}(...);\n"));
    }
    out.push('\n');

    // Global function table
    out.push_str(&format!(
        "static void* GUikaFuncTable[UikaFuncId::FUNC_COUNT];\n\n"
    ));

    // Fill function
    out.push_str("void UikaFillFuncTable() {\n");
    for entry in entries {
        let const_name =
            crate::rust_gen::func_ids::func_id_const_name(&entry.class_name, &entry.func_name);
        let c_name = cpp_wrapper_name(&entry.class_name, &entry.func_name);
        out.push_str(&format!(
            "    GUikaFuncTable[UikaFuncId::{const_name}] = (void*)&{c_name};\n"
        ));
    }
    out.push_str("}\n\n");

    // Getter for the table pointer
    out.push_str("void** UikaGetFuncTable() {\n");
    out.push_str("    return GUikaFuncTable;\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "uint32_t UikaGetFuncCount() {{\n    return UikaFuncId::FUNC_COUNT;\n}}\n"
    ));

    out
}
