// Auto-generated by uika-codegen. Do not edit.

#![allow(non_camel_case_types, non_snake_case, dead_code, unused_imports)]

pub mod func_ids;

#[cfg(feature = "core")]
pub mod core_ue;

#[cfg(feature = "engine")]
pub mod engine;

#[cfg(target_arch = "wasm32")]
pub mod wasm_fn_imports;

pub mod manual;

