[package]
name = "uika"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Rust bindings for Unreal Engine 5.7+"

[dependencies]
uika-ffi = { workspace = true }
uika-runtime = { workspace = true }
uika-macros = { workspace = true }
uika-bindings = { workspace = true }
uika-ue-flags = { workspace = true }
glam = { workspace = true }
inventory = { workspace = true }

[features]
default = ["core", "engine"]
core = ["uika-bindings/core"]
engine = ["core", "input", "uika-bindings/engine"]
physics-core = ["engine", "uika-bindings/physics-core"]
input = ["core", "uika-bindings/input"]
slate = ["core", "uika-bindings/slate"]
umg = ["slate", "uika-bindings/umg"]
niagara = ["engine", "uika-bindings/niagara"]
gameplay-abilities = ["engine", "uika-bindings/gameplay-abilities"]
level-sequence = ["engine", "uika-bindings/level-sequence"]
cinematic = ["engine", "uika-bindings/cinematic"]
movie = ["engine", "uika-bindings/movie"]
